# Generated by Django 4.0.3 on 2022-03-18 05:26
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('relation', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'activity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('max_phase', models.IntegerField(blank=True, null=True)),
                ('structure', models.CharField(blank=True, max_length=4000, null=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27, null=True)),
            ],
            options={
                'db_table': 'molecule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('organism', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': False,
            },
        ),
    ]
